### ISSUE TITLE
Apply a FOSS license

### ISSUE THREAD

**Issue by tcarrio** [Kefimochi/MDN-Search#5]
It would be nice to see a license applied to this codebase. I'd be interested in extending the feature set and contributing changes back to this repository if possible. The default behaviour of unlicensed software allows no derivative work, where projects that are truly open source allow modification of the code should users want to add a feature myself. Consider looking at GitHubs page for [Choosing a License](https://choosealicense.com/). Unless you have trademarking or company assets to protect, typically the MIT license and GPLv3 will suffice.

Also, nice work on this 👌

**Comment by kefimochi** [comment]
@tcarrio Does this seem alright? 🙂 https://github.com/kefimochi/MDN-Search/blob/master/LICENSE

**Comment by tcarrio** [comment]
You should fill in your name for the copyright information (full name or just `kefimochi`, if you would prefer), as well as the year. Otherwise, looking good :+1:

**Comment by kefimochi** [comment]
Didn't even notice that, thank you for bringing it up! 😅
